export const minersData = [
    { id: 1, name: "John Smith", section: "Section A", helmetId: "H-1001", shiftId: 1 },
    { id: 2, name: "Sarah Johnson", section: "Safety", helmetId: "H-1002", shiftId: 2 },
    { id: 3, name: "Michael Brown", section: "Section B", helmetId: "H-1003", shiftId: 3 },
    { id: 4, name: "Emily Davis", section: "Environmental", helmetId: "H-1004", shiftId: 4 },
    { id: 5, name: "Robert Wilson", section: "Maintenance", helmetId: "", shiftId: 5 },
    { id: 6, name: "Lisa Thompson", section: "Section C", helmetId: "", shiftId: null },
    { id: 7, name: "David Garcia", section: "Section A", helmetId: "", shiftId: 1 },
    { id: 8, name: "Thomas Wright", section: "Section A", helmetId: "", shiftId: 1 },
    { id: 9, name: "James Lee", section: "Section A", helmetId: "", shiftId: 1 },
    { id: 10, name: "Maria Rodriguez", section: "Section B", helmetId: "", shiftId: 2 },
    { id: 11, name: "Robert Chen", section: "Section B", helmetId: "", shiftId: 2 },
    { id: 12, name: "Lisa Thompson", section: "Section C", helmetId: "", shiftId: 3 },
    { id: 13, name: "Kevin Wilson", section: "Section A", helmetId: "", shiftId: 4 },
    { id: 14, name: "Anna Kim", section: "Section D", helmetId: "", shiftId: null },
    { id: 15, name: "Carlos Mendez", section: "Section D", helmetId: "", shiftId: null },
  ]

 export const initialHelmetsData = [
    {
      id: "H-1001",
      status: "active",
      batteryLevel: 85,
      lastMaintenance: "2023-12-10",
      nextMaintenance: "2024-03-10",
      assignedTo: "John Smith",
      minerId: 1,
      location: "Section A",
      signalStrength: 92,
      sensors: ["Temperature", "Gas", "Impact", "Emergency Button"],
      model: "SmartHelmet Pro",
      purchaseDate: "2023-01-15",
    },
    {
      id: "H-1002",
      status: "active",
      batteryLevel: 72,
      lastMaintenance: "2023-11-05",
      nextMaintenance: "2024-02-05",
      assignedTo: "Sarah Johnson",
      minerId: 2,
      location: "Safety",
      signalStrength: 88,
      sensors: ["Temperature", "Gas", "Impact", "Motion", "Emergency Button"],
      model: "SmartHelmet Pro",
      purchaseDate: "2023-01-20",
    },
    {
      id: "H-1003",
      status: "maintenance",
      batteryLevel: 45,
      lastMaintenance: "2024-01-15",
      nextMaintenance: "2024-04-15",
      assignedTo: "Michael Brown",
      minerId: 3,
      location: "Maintenance Bay",
      signalStrength: 0,
      sensors: ["Temperature", "Gas", "Impact", "Emergency Button"],
      model: "SmartHelmet Standard",
      purchaseDate: "2022-11-10",
    },
    {
      id: "H-1004",
      status: "active",
      batteryLevel: 91,
      lastMaintenance: "2023-12-20",
      nextMaintenance: "2024-03-20",
      assignedTo: "Emily Davis",
      minerId: 4,
      location: "Environmental",
      signalStrength: 95,
      sensors: ["Temperature", "Gas", "Impact", "Air Quality", "Emergency Button"],
      model: "SmartHelmet Pro+",
      purchaseDate: "2023-02-05",
    },
    {
      id: "H-1005",
      status: "inactive",
      batteryLevel: 0,
      lastMaintenance: "2023-10-10",
      nextMaintenance: "2024-01-10",
      assignedTo: "",
      minerId: null,
      location: "Storage",
      signalStrength: 0,
      sensors: ["Temperature", "Gas", "Emergency Button"],
      model: "SmartHelmet Standard",
      purchaseDate: "2022-08-15",
    },
    {
      id: "H-1006",
      status: "active",
      batteryLevel: 68,
      lastMaintenance: "2023-11-25",
      nextMaintenance: "2024-02-25",
      assignedTo: "",
      minerId: null,
      location: "Section B",
      signalStrength: 78,
      sensors: ["Temperature", "Gas", "Impact", "Emergency Button"],
      model: "SmartHelmet Pro",
      purchaseDate: "2023-03-10",
    },
  ]